services:
  # Front-end : React App
  web-server:
  # 자신이 만든 이미지 이름을 정확히 기입. (아마도 dockerhub 에 올려져있는 이미지 이름임)
    image: summerchoco/travelbuddy-frontend
    # build:
    #   context: ./travelbuddy-frontend
    #   dockerfile: Dockerfile
    container_name: travelbuddy-frontend
    ports:
      - "80:3000"

  # Back-end : SpringBoot REST API Server
  backend-server:
  # 자신이 만든 이미지 이름을 정확히 기입. (아마도 dockerhub 에 올려져있는 이미지 이름임)
    image: summerchoco/travelbuddy-backend
    # build:
    #   context: ./travelbuddy-backend
    #   dockerfile: Dockerfile
    container_name: travelbuddy-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tbdb
      SPRING_DATASOURCE_USERNAME: travelbuddy
      SPRING_DATASOURCE_PASSWORD: travelbuddy
    ports:
      - "8080:8080"
    volumes:
      - ./static/productimgs:/springboot-app/productimgs
    depends_on:
      - database-server

  # Database : MySQL DBMS
  database-server:
    image: mysql:8.0.38
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: tbdb
      MYSQL_USER: travelbuddy
      MYSQL_PASSWORD: travelbuddy
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

volumes:
  mysql-data: