### POST request: admin user login (localhost)
POST localhost:8080/auth/login
Content-Type:application/json
Accept:*/*
Access-Control-Allow-Origin:*

{
  "memberName": "admin",
  "memberPassword": "1234"
}

### POST request: general user login (localhost)
POST localhost:8080/auth/login
Content-Type:application/json
Accept:*/*
Access-Control-Allow-Origin:*

{
  "memberName": "user01",
  "memberPassword": "1234"
}